// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentCarServer.Insfractructure.Context;

#nullable disable

namespace RentCarServer.Insfractructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260412115415_i_created_login_token_table")]
    partial class i_created_login_token_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RentCarServer.Domain.LoginTokens.LoginToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ExpiresDate", "RentCarServer.Domain.LoginTokens.LoginToken.ExpiresDate#ExpiresDate", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("value")
                                .HasColumnType("datetimeoffset");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "IsActive", "RentCarServer.Domain.LoginTokens.LoginToken.IsActive#IsActive", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("value")
                                .HasColumnType("bit");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token", "RentCarServer.Domain.LoginTokens.LoginToken.Token#Token", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("value")
                                .IsRequired()
                                .HasColumnType("nvarchar(MAX)");
                        });

                    b.HasKey("Id");

                    b.ToTable("LoginToken");
                });

            modelBuilder.Entity("RentCarServer.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Email", "RentCarServer.Domain.Users.User.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(MAX)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "FirstName", "RentCarServer.Domain.Users.User.FirstName#FirstName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(MAX)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ForgotPasswordCode", "RentCarServer.Domain.Users.User.ForgotPasswordCode#ForgotPasswordCode", b1 =>
                        {
                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ForgotPasswordDate", "RentCarServer.Domain.Users.User.ForgotPasswordDate#ForgotPasswordDate", b1 =>
                        {
                            b1.Property<DateTimeOffset>("Value")
                                .HasColumnType("datetimeoffset");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "FullName", "RentCarServer.Domain.Users.User.FullName#FullName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(MAX)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "IsForgotPasswordCompleted", "RentCarServer.Domain.Users.User.IsForgotPasswordCompleted#IsForgotPasswordCompleted", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("Value")
                                .HasColumnType("bit");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "LastName", "RentCarServer.Domain.Users.User.LastName#LastName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(MAX)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Password", "RentCarServer.Domain.Users.User.Password#Password", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<byte[]>("PasswordHash")
                                .IsRequired()
                                .HasColumnType("varbinary(max)");

                            b1.Property<byte[]>("PasswordSalt")
                                .IsRequired()
                                .HasColumnType("varbinary(max)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "UserName", "RentCarServer.Domain.Users.User.UserName#UserName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(MAX)");
                        });

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
